public class ApexxDmlOperations {
    
    /*public static void DeleteAccount(){
        
        Account AccountObj = [select ID,Name from Account where id='0012w00001cHR5JAAW'];
        
        delete AccountObj;
        
        System.debug('Account Deleted:'+AccountObj);
        
       
    }
    
    Public static void UndeleteAccount(){
        
        Account acc = [select ID ,Name from account where Name='Apex learning' ALL ROWS];
        
        undelete acc;
        
        system.debug('Account undelete Successfully'+acc);
    }*/

}